- name: AWS EC2 Deployment
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  tasks: 
    - set_fact:
        ansible_python_interpreter: /usr/bin/python3
    - name: Create Instance
      amazon.aws.ec2:
        key_name: aws_instance_Ansible
        instance_type: t2.micro
        image: ami-0dacb0c129b49f529
        region: eu-central-1
        wait: yes
        group: default
        count: 3
        assign_public_ip: yes
        aws_access_key: lookup('env', 'AWS_ACCESS_KEY')
        aws_secret_key: lookup('env', 'AWS_SECRET_KEY')
      register: ec2
      
