- name: AWS EC2 Deployment
- hosts: localhost
  tasks: 
    - name: Create Instance
      amazon.aws.ec2:
        key_name: mykey
        instance_type: t2.micro
        image: ami-123456
        wait: yes
        group: webserver
        count: 3
        assign_public_ip: yes
      register: ec2
