name: Spotify Playlist CI/CD
on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  ansible-deployment:
    needs: docker
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_TOKEN:    ${{ secrets.REGISTRY_GITHUB_TOKEN }}
      IMAGE_NAME:      ${{ github.repository }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install boto & boto3
        run: python -m pip install boto boto3
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: deploy.yml
          directory: ./
