name: Spotify Playlist CI/CD
on: [push]
jobs:
  Ansible-Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install boto & boto3
        run: python -m pip install boto boto3
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: deploy.yml
          directory: ./
