name: Spotify Playlist CI/CD
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: julianyaman/spotify-dhbw-web-app:latest
  Ansible-Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install boto & boto3
        run: python -m pip install boto boto3
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: deploy.yml
          directory: ./
